/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as LayoutTaskNewRouteImport } from './routes/_layout.task/new'
import { Route as LayoutTaskIdRouteImport } from './routes/_layout.task/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskNewRoute = LayoutTaskNewRouteImport.update({
  id: '/task/new',
  path: '/task/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTaskIdRoute = LayoutTaskIdRouteImport.update({
  id: '/task/$id',
  path: '/task/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/task/$id': typeof LayoutTaskIdRoute
  '/task/new': typeof LayoutTaskNewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof LayoutIndexRoute
  '/task/$id': typeof LayoutTaskIdRoute
  '/task/new': typeof LayoutTaskNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/task/$id': typeof LayoutTaskIdRoute
  '/_layout/task/new': typeof LayoutTaskNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/task/$id' | '/task/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/task/$id' | '/task/new'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/'
    | '/_layout/task/$id'
    | '/_layout/task/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/new': {
      id: '/_layout/task/new'
      path: '/task/new'
      fullPath: '/task/new'
      preLoaderRoute: typeof LayoutTaskNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/task/$id': {
      id: '/_layout/task/$id'
      path: '/task/$id'
      fullPath: '/task/$id'
      preLoaderRoute: typeof LayoutTaskIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutTaskIdRoute: typeof LayoutTaskIdRoute
  LayoutTaskNewRoute: typeof LayoutTaskNewRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutTaskIdRoute: LayoutTaskIdRoute,
  LayoutTaskNewRoute: LayoutTaskNewRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
